Feature/landing page
maykinmedia/sharing-configs-api pull request #13
Opened 2022-06-02 15:38 UTC by annashamray

fixes https://github.com/maykinmedia/sharing-configs/issues/22

2022-06-14 11:05 UTC, joeribekker requested changes
2 minor requests, otherwise looks good and I think it's BEM-ish :)

2022-06-14 11:05 UTC, joeribekker commented on src/sharing/scss/_app.scss
> +  font-weight: 500;
Can we make the font-weight for h1=300?

2022-06-14 11:05 UTC, joeribekker commented on src/sharing/scss/_app.scss
> +  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
Can we include a Google font, Roboto, to stay close to what it is now?

```suggestion
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
```

2022-06-14 16:14 UTC, annashamray commented on src/sharing/scss/_app.scss
> +  font-weight: 500;
Done, but I don't see the difference :)

2022-06-16 11:49 UTC, joeribekker commented
> Done, but I don't see the difference :)

That's because you didn't implement the Roboto font, you only said to CSS to use it. Please also add the Roboto font code.

2022-06-24 09:20 UTC, joeribekker approved these changes

2022-06-24 09:21 UTC, merged